### ISSUE TITLE
Vagrant up doesn't bring the machine up as it probably should

### ISSUE THREAD

**Issue by localheinz** [zendframework/modules.zendframework.com#212]
```
$ vagrant up
```

doesn't result in the machine being brought up as expected.

This has already been mentioned in https://github.com/zendframework/modules.zendframework.com/pull/187#issuecomment-51773218, but as pointed out there, this is a deal breaker for people willing to contribute.

Can someone please have a look?

Here's the console output of my attempt:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'debian-wheezy72-x64-vbox43'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: moduleszendframeworkcom_default_1416328545092_76185
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 6161 (adapter 1)
    default: 80 => 8082 (adapter 1)
    default: 3306 => 3308 (adapter 1)
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /var/www => /Users/am/Sites/zendframework/modules.zendframework.com
    default: /vagrant => /Users/am/Sites/zendframework/modules.zendframework.com
    default: /tmp/vagrant-puppet-3/manifests => /Users/am/Sites/zendframework/modules.zendframework.com/puphpet/puppet
==> default: Running provisioner: shell...
    default: Running: /var/folders/fb/q922_rc10fjf303z816ybdmc0000gn/T/vagrant-shell20141118-53922-12vqmsm.sh
==> default: stdin: is not a tty
==> default: 
==> default:  ____        ____  _   _ ____      _      generated using
==> default: |  _ \ _   _|  _ \| | | |  _ \ ___| |_   ___ ___  _ __ ___
==> default: | |_) | | | | |_) | |_| | |_) / _ \ __| / __/ _ \| '_ ` _ \
==> default: |  __/| |_| |  __/|  _  |  __/  __/ |_ | (_| (_) | | | | | |
==> default: |_|    \__,_|_|   |_| |_|_|   \___|\__(_)___\___/|_| |_| |_|
==> default: Created directory /.puphpet-stuff
==> default: Running initial-setup apt-get update
==> default: Finished running initial-setup apt-get update
==> default: Running provisioner: shell...
    default: Running: /var/folders/fb/q922_rc10fjf303z816ybdmc0000gn/T/vagrant-shell20141118-53922-10j78zv.sh
==> default: stdin: is not a tty
==> default: Downloading http://apt.puppetlabs.com/puppetlabs-release-wheezy.deb
==> default: Finished downloading http://apt.puppetlabs.com/puppetlabs-release-wheezy.deb
==> default: Running update-puppet apt-get update
==> default: Finished running update-puppet apt-get update
==> default: Updating Puppet to latest version
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Finished updating puppet to latest version: Puppet v3.7.3
==> default: Created empty file /.puphpet-stuff/update-puppet
==> default: Running provisioner: shell...
    default: Running: /var/folders/fb/q922_rc10fjf303z816ybdmc0000gn/T/vagrant-shell20141118-53922-q4pjpt.sh
==> default: stdin: is not a tty
==> default: Installing git
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Finished installing git
==> default: Copied Puppetfile
==> default: Installing base packages for librarian
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Finished installing base packages for librarian
==> default: Installing librarian-puppet
==> default: Finished installing librarian-puppet
==> default: Running initial librarian-puppet
==> default: Finished running initial librarian-puppet
==> default: Replacing puppetlabs-git module with custom
==> default: Cloning into '/etc/puppet/modules/git'...
==> default: Finished replacing puppetlabs-git module with custom
==> default: Running provisioner: puppet...
==> default: Running Puppet with manifest.pp...
==> default: stdin: is not a tty
==> default: Warning: Setting templatedir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
==> default:    (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1139:in `issue_deprecation_warning')
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Info: Loading facts
==> default: Error: PHP: cannot set both source and template on node packer-virtualbox.vagrantup.com
==> default: Error: PHP: cannot set both source and template on node packer-virtualbox.vagrantup.com
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by gianarb** [comment]
@localheinz ping! :) I use this configuration, does it work for you?
