### ISSUE TITLE
A New 500 Error on the modules page

### ISSUE THREAD

**Issue by GeeH** [zendframework/modules.zendframework.com#302]
```
2015-01-11T11:29:20-07:00 ERR (3): Exception:n1: Not FoundnTrace:n#0 [internal function]: EdpGithub\Listener\Error->postSend(Object(Zend\EventManager\Event))
#1 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\EventManager\Event))
#2 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('post.send', Object(Zend\EventManager\Event), NULL)
#3 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Http/Client.php(135): Zend\EventManager\EventManager->trigger('post.send', Object(Zend\Http\Response))
#4 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Http/Client.php(63): EdpGithub\Http\Client->request('repos/neoglez/B...', Array, 'GET', Array)
#5 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Api/AbstractApi.php(22): EdpGithub\Http\Client->get('repos/neoglez/B...', Array, Array)
#6 /var/www/modules/vendor/evandotpro/edp-github/src/EdpGithub/Api/Repos.php(35): EdpGithub\Api\AbstractApi->get('repos/neoglez/B...')
#7 /var/www/modules/module/Application/src/Application/Service/RepositoryRetriever.php(73): EdpGithub\Api\Repos->content('neoglez', 'BatchManager', 'LICENSE')
#8 /var/www/modules/module/Application/src/Application/Service/RepositoryRetriever.php(55): Application\Service\RepositoryRetriever->getRepositoryFileMetadata('neoglez', 'BatchManager', 'LICENSE')
#9 /var/www/modules/module/ZfModule/src/ZfModule/Controller/IndexController.php(61): Application\Service\RepositoryRetriever->getRepositoryFileContent('neoglez', 'BatchManager', 'LICENSE')
#10 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractActionController.php(83): ZfModule\Controller\IndexController->viewAction()
#11 [internal function]: Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
#12 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#13 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#14 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php(116): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#15 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php(113): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
#16 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#17 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(468): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#18 /var/www/modules/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php(207): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#19 /var/www/modules/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php(313): Zend\EventManager\EventManager->trigger('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#20 /var/www/modules/public/index.php(17): Zend\Mvc\Application->run()
#21 {main}
```

Any ideas?

**Comment by GeeH** [comment]
For info, I just got Kairos to deploy latest version of the code from master so we knew where we were, and we get this error.

**Comment by localheinz** [comment]
@GeeH 

Thanks for the update!

**Comment by ins0** [comment]
looks like the github cache is missing/not configured?

**Comment by localheinz** [comment]
Maybe related to #299? 

@GeeH 

Maybe we should revert it for now?

**Comment by GeeH** [comment]
Rolled back, but now we has API rate limiting again - ARGH!

**Comment by ins0** [comment]
@GeeH please look at #288 - the Github API doc says ``Invalid tokens will return 404 NOT FOUND.`` this maybe explain the ``Not Found`` error message - i can't repoduce this error - even with #299 there is no error - the only difference is that i use local a different oauth key + secret
